### PR TITLE
Fix wrong assert, remove unneeded assert and fix serialization test

### LINKED ISSUE #194: Bug in https://github.com/vmware/concord-bft/blob/dc77051f87e4c32cc7418dc4e44530d2cbc68230/bftengine/src/bftengine/PersistentStorageImp.cpp#L875
The following assert is incorrect: https://github.com/vmware/concord-bft/blob/dc77051f87e4c32cc7418dc4e44530d2cbc68230/bftengine/src/bftengine/PersistentStorageImp.cpp#L875

You probably want to write "Assert(hasDescriptorOfLastExitFromView() || desc.view == 0)”

### PR DESCRIPTION
**Pull request by salieri11**
This PR fixes the incorrect assert when verifying descriptor of last exit from the view.
Moreover, the unneeded assert is removed.

All tests passed, including skvbc_persistence

Fixes #194

### CODE REVIEW

File: bftengine/tests/testSerialization/TestSerialization.cpp [hunk 1]
```diff
@@ -358,12 +358,13 @@ void testSetDescriptors(bool toSet) {
...
   SeqNum lastStable = 48;
-  auto *viewChangeMsg = new ViewChangeMsg(senderId, viewNum, lastStable);
+  auto *viewChangeMsg = new ViewChangeMsg(senderId, viewNum + 1, lastStable);
   DescriptorOfLastExitFromView lastExitFromViewDesc(viewNum, lastExitStableNum, lastExitExecNum, elements,
                                                     viewChangeMsg, lastExitStableLowerBound);
 
   ViewChangeMsgsVector msgs;
-  ViewNum newViewNum = 6;
+  ViewNum newViewNum = 1
+  ;
```
Comment (yuliasherman) [inline bftengine/tests/testSerialization/TestSerialization.cpp]: Please move ';' string up.

File: bftengine/src/bftengine/PersistentStorageImp.cpp [hunk 2]
```diff
@@ -615,7 +615,6 @@ PersistentStorageImp::getAndAllocateDescriptorOfLastExitFromView() {
 
 DescriptorOfLastNewView
 PersistentStorageImp::getAndAllocateDescriptorOfLastNewView() {
-  Assert(getIsAllowed());
```
Comment (andrewjstone) [inline bftengine/src/bftengine/PersistentStorageImp.cpp]: Haha, I could have perfomed this fix :) I guess it's like the repairman charging a $1 for the fix and $99 for knowing where to kick the appliance.

Comment (yuliasherman) [reply bftengine/src/bftengine/PersistentStorageImp.cpp]: Exactly, this knowledge worth its price :-)
